version: '3.7'
services:
  reptile1:
    container_name: system_test_reptile1
    build:
      context: ..
    ports:
      - "2600:2600"
    environment:
      - 'SERVERS=172.28.1.1 172.28.1.2 172.28.1.3'
    networks:
      reptile_net:
        ipv4_address: 172.28.1.1

  reptile2:
    container_name: system_test_reptile2
    build:
      context: ..
    ports:
      - "2700:2600"
    environment:
      - 'SERVERS=172.28.1.1 172.28.1.2 172.28.1.3'
    networks:
      reptile_net:
        ipv4_address: 172.28.1.2

  reptile3:
    container_name: system_test_reptile3
    build:
      context: ..
    ports:
      - "2800:2600"
    environment:
      - 'SERVERS=172.28.1.1 172.28.1.2 172.28.1.3'
    networks:
      reptile_net:
        ipv4_address: 172.28.1.3

networks:
  reptile_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16