// Code generated by protoc-gen-go. DO NOT EDIT.
// source: server/reptile.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PrepareReplica struct {
	View                 uint32   `protobuf:"varint,1,opt,name=view,proto3" json:"view,omitempty"`
	ClientMessage        string   `protobuf:"bytes,2,opt,name=clientMessage,proto3" json:"clientMessage,omitempty"`
	OperationNum         uint32   `protobuf:"varint,3,opt,name=operationNum,proto3" json:"operationNum,omitempty"`
	CommitNum            uint32   `protobuf:"varint,4,opt,name=commitNum,proto3" json:"commitNum,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrepareReplica) Reset()         { *m = PrepareReplica{} }
func (m *PrepareReplica) String() string { return proto.CompactTextString(m) }
func (*PrepareReplica) ProtoMessage()    {}
func (*PrepareReplica) Descriptor() ([]byte, []int) {
	return fileDescriptor_0100d9e854fa7d80, []int{0}
}

func (m *PrepareReplica) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrepareReplica.Unmarshal(m, b)
}
func (m *PrepareReplica) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrepareReplica.Marshal(b, m, deterministic)
}
func (m *PrepareReplica) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrepareReplica.Merge(m, src)
}
func (m *PrepareReplica) XXX_Size() int {
	return xxx_messageInfo_PrepareReplica.Size(m)
}
func (m *PrepareReplica) XXX_DiscardUnknown() {
	xxx_messageInfo_PrepareReplica.DiscardUnknown(m)
}

var xxx_messageInfo_PrepareReplica proto.InternalMessageInfo

func (m *PrepareReplica) GetView() uint32 {
	if m != nil {
		return m.View
	}
	return 0
}

func (m *PrepareReplica) GetClientMessage() string {
	if m != nil {
		return m.ClientMessage
	}
	return ""
}

func (m *PrepareReplica) GetOperationNum() uint32 {
	if m != nil {
		return m.OperationNum
	}
	return 0
}

func (m *PrepareReplica) GetCommitNum() uint32 {
	if m != nil {
		return m.CommitNum
	}
	return 0
}

type PrepareOk struct {
	View                 uint32   `protobuf:"varint,1,opt,name=view,proto3" json:"view,omitempty"`
	OperationNum         uint32   `protobuf:"varint,2,opt,name=operationNum,proto3" json:"operationNum,omitempty"`
	ReplicaNum           uint32   `protobuf:"varint,3,opt,name=replicaNum,proto3" json:"replicaNum,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrepareOk) Reset()         { *m = PrepareOk{} }
func (m *PrepareOk) String() string { return proto.CompactTextString(m) }
func (*PrepareOk) ProtoMessage()    {}
func (*PrepareOk) Descriptor() ([]byte, []int) {
	return fileDescriptor_0100d9e854fa7d80, []int{1}
}

func (m *PrepareOk) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrepareOk.Unmarshal(m, b)
}
func (m *PrepareOk) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrepareOk.Marshal(b, m, deterministic)
}
func (m *PrepareOk) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrepareOk.Merge(m, src)
}
func (m *PrepareOk) XXX_Size() int {
	return xxx_messageInfo_PrepareOk.Size(m)
}
func (m *PrepareOk) XXX_DiscardUnknown() {
	xxx_messageInfo_PrepareOk.DiscardUnknown(m)
}

var xxx_messageInfo_PrepareOk proto.InternalMessageInfo

func (m *PrepareOk) GetView() uint32 {
	if m != nil {
		return m.View
	}
	return 0
}

func (m *PrepareOk) GetOperationNum() uint32 {
	if m != nil {
		return m.OperationNum
	}
	return 0
}

func (m *PrepareOk) GetReplicaNum() uint32 {
	if m != nil {
		return m.ReplicaNum
	}
	return 0
}

func init() {
	proto.RegisterType((*PrepareReplica)(nil), "pb.PrepareReplica")
	proto.RegisterType((*PrepareOk)(nil), "pb.PrepareOk")
}

func init() {
	proto.RegisterFile("server/reptile.proto", fileDescriptor_0100d9e854fa7d80)
}

var fileDescriptor_0100d9e854fa7d80 = []byte{
	// 207 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x4b, 0x4a, 0xc7, 0x30,
	0x10, 0xc6, 0x4d, 0xfd, 0x63, 0xe9, 0x60, 0x5d, 0x0c, 0x2e, 0x8a, 0x88, 0x94, 0xe0, 0xa2, 0xab,
	0x08, 0xba, 0xf2, 0x10, 0x5a, 0xe9, 0x0d, 0xd2, 0x30, 0x48, 0xe8, 0x23, 0x61, 0x1a, 0xeb, 0x25,
	0x3c, 0xb4, 0x18, 0x2b, 0x6d, 0xa5, 0xbb, 0xe1, 0xc7, 0xc7, 0x7c, 0x0f, 0xb8, 0x9e, 0x88, 0x67,
	0xe2, 0x07, 0x26, 0x1f, 0x6c, 0x4f, 0xca, 0xb3, 0x0b, 0x0e, 0x13, 0xdf, 0xca, 0x2f, 0x01, 0x57,
	0x6f, 0x4c, 0x5e, 0x33, 0x35, 0xe4, 0x7b, 0x6b, 0x34, 0x22, 0x9c, 0x66, 0x4b, 0x9f, 0x85, 0x28,
	0x45, 0x95, 0x37, 0xf1, 0xc6, 0x7b, 0xc8, 0x4d, 0x6f, 0x69, 0x0c, 0x2f, 0x34, 0x4d, 0xfa, 0x9d,
	0x8a, 0xa4, 0x14, 0x55, 0xd6, 0xec, 0x21, 0x4a, 0xb8, 0x74, 0x9e, 0x58, 0x07, 0xeb, 0xc6, 0xd7,
	0x8f, 0xa1, 0x38, 0x8f, 0x1f, 0x76, 0x0c, 0x6f, 0x21, 0x33, 0x6e, 0x18, 0x6c, 0xf8, 0x11, 0x9c,
	0xa2, 0x60, 0x05, 0xd2, 0x40, 0xb6, 0xa4, 0xa9, 0xbb, 0xc3, 0x20, 0xff, 0x2d, 0x92, 0x03, 0x8b,
	0x3b, 0x00, 0xfe, 0xed, 0xb2, 0x86, 0xd8, 0x90, 0xc7, 0x67, 0x48, 0xff, 0xba, 0x2a, 0x48, 0x17,
	0x3f, 0x44, 0xe5, 0x5b, 0xb5, 0x9f, 0xe2, 0x26, 0xdf, 0xb0, 0xba, 0x93, 0x67, 0xed, 0x45, 0x5c,
	0xee, 0xe9, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x15, 0x65, 0x64, 0xa4, 0x51, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ReplicaClient is the client API for Replica service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ReplicaClient interface {
	Prepare(ctx context.Context, in *PrepareReplica, opts ...grpc.CallOption) (*PrepareOk, error)
}

type replicaClient struct {
	cc grpc.ClientConnInterface
}

func NewReplicaClient(cc grpc.ClientConnInterface) ReplicaClient {
	return &replicaClient{cc}
}

func (c *replicaClient) Prepare(ctx context.Context, in *PrepareReplica, opts ...grpc.CallOption) (*PrepareOk, error) {
	out := new(PrepareOk)
	err := c.cc.Invoke(ctx, "/pb.Replica/Prepare", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReplicaServer is the server API for Replica service.
type ReplicaServer interface {
	Prepare(context.Context, *PrepareReplica) (*PrepareOk, error)
}

// UnimplementedReplicaServer can be embedded to have forward compatible implementations.
type UnimplementedReplicaServer struct {
}

func (*UnimplementedReplicaServer) Prepare(ctx context.Context, req *PrepareReplica) (*PrepareOk, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Prepare not implemented")
}

func RegisterReplicaServer(s *grpc.Server, srv ReplicaServer) {
	s.RegisterService(&_Replica_serviceDesc, srv)
}

func _Replica_Prepare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrepareReplica)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplicaServer).Prepare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Replica/Prepare",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplicaServer).Prepare(ctx, req.(*PrepareReplica))
	}
	return interceptor(ctx, in, info, handler)
}

var _Replica_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Replica",
	HandlerType: (*ReplicaServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Prepare",
			Handler:    _Replica_Prepare_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "server/reptile.proto",
}
