// Code generated by protoc-gen-go. DO NOT EDIT.
// source: reptile.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ClientRequest struct {
	Operation            string   `protobuf:"bytes,1,opt,name=operation,proto3" json:"operation,omitempty"`
	ClientId             string   `protobuf:"bytes,2,opt,name=clientId,proto3" json:"clientId,omitempty"`
	RequestNum           uint32   `protobuf:"varint,3,opt,name=requestNum,proto3" json:"requestNum,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientRequest) Reset()         { *m = ClientRequest{} }
func (m *ClientRequest) String() string { return proto.CompactTextString(m) }
func (*ClientRequest) ProtoMessage()    {}
func (*ClientRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f764a93c57505ffe, []int{0}
}

func (m *ClientRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientRequest.Unmarshal(m, b)
}
func (m *ClientRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientRequest.Marshal(b, m, deterministic)
}
func (m *ClientRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientRequest.Merge(m, src)
}
func (m *ClientRequest) XXX_Size() int {
	return xxx_messageInfo_ClientRequest.Size(m)
}
func (m *ClientRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ClientRequest proto.InternalMessageInfo

func (m *ClientRequest) GetOperation() string {
	if m != nil {
		return m.Operation
	}
	return ""
}

func (m *ClientRequest) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *ClientRequest) GetRequestNum() uint32 {
	if m != nil {
		return m.RequestNum
	}
	return 0
}

type ClientResponse struct {
	Response             string   `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	RequestNum           uint32   `protobuf:"varint,2,opt,name=requestNum,proto3" json:"requestNum,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientResponse) Reset()         { *m = ClientResponse{} }
func (m *ClientResponse) String() string { return proto.CompactTextString(m) }
func (*ClientResponse) ProtoMessage()    {}
func (*ClientResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f764a93c57505ffe, []int{1}
}

func (m *ClientResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientResponse.Unmarshal(m, b)
}
func (m *ClientResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientResponse.Marshal(b, m, deterministic)
}
func (m *ClientResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientResponse.Merge(m, src)
}
func (m *ClientResponse) XXX_Size() int {
	return xxx_messageInfo_ClientResponse.Size(m)
}
func (m *ClientResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ClientResponse proto.InternalMessageInfo

func (m *ClientResponse) GetResponse() string {
	if m != nil {
		return m.Response
	}
	return ""
}

func (m *ClientResponse) GetRequestNum() uint32 {
	if m != nil {
		return m.RequestNum
	}
	return 0
}

func init() {
	proto.RegisterType((*ClientRequest)(nil), "pb.ClientRequest")
	proto.RegisterType((*ClientResponse)(nil), "pb.ClientResponse")
}

func init() {
	proto.RegisterFile("reptile.proto", fileDescriptor_f764a93c57505ffe)
}

var fileDescriptor_f764a93c57505ffe = []byte{
	// 176 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x4a, 0x2d, 0x28,
	0xc9, 0xcc, 0x49, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x52, 0xca, 0xe4,
	0xe2, 0x75, 0xce, 0xc9, 0x4c, 0xcd, 0x2b, 0x09, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x92,
	0xe1, 0xe2, 0xcc, 0x2f, 0x48, 0x2d, 0x4a, 0x2c, 0xc9, 0xcc, 0xcf, 0x93, 0x60, 0x54, 0x60, 0xd4,
	0xe0, 0x0c, 0x42, 0x08, 0x08, 0x49, 0x71, 0x71, 0x24, 0x83, 0x95, 0x7b, 0xa6, 0x48, 0x30, 0x81,
	0x25, 0xe1, 0x7c, 0x21, 0x39, 0x2e, 0xae, 0x22, 0x88, 0x21, 0x7e, 0xa5, 0xb9, 0x12, 0xcc, 0x0a,
	0x8c, 0x1a, 0xbc, 0x41, 0x48, 0x22, 0x4a, 0x3e, 0x5c, 0x7c, 0x30, 0xab, 0x8a, 0x0b, 0xf2, 0xf3,
	0x8a, 0x53, 0x41, 0xa6, 0x15, 0x41, 0xd9, 0x50, 0xab, 0xe0, 0x7c, 0x34, 0xd3, 0x98, 0xd0, 0x4d,
	0x33, 0xb2, 0xe5, 0x62, 0x0f, 0x82, 0xf8, 0x46, 0xc8, 0x08, 0xc4, 0x84, 0xb8, 0x5e, 0x50, 0xaf,
	0x20, 0x49, 0x0f, 0xc5, 0x43, 0x52, 0x42, 0xc8, 0x42, 0x10, 0xc3, 0x95, 0x18, 0x92, 0xd8, 0xc0,
	0x41, 0x60, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x8c, 0x9d, 0x38, 0x15, 0x13, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ReptileClient is the client API for Reptile service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ReptileClient interface {
	Request(ctx context.Context, in *ClientRequest, opts ...grpc.CallOption) (*ClientResponse, error)
}

type reptileClient struct {
	cc grpc.ClientConnInterface
}

func NewReptileClient(cc grpc.ClientConnInterface) ReptileClient {
	return &reptileClient{cc}
}

func (c *reptileClient) Request(ctx context.Context, in *ClientRequest, opts ...grpc.CallOption) (*ClientResponse, error) {
	out := new(ClientResponse)
	err := c.cc.Invoke(ctx, "/pb.Reptile/Request", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReptileServer is the server API for Reptile service.
type ReptileServer interface {
	Request(context.Context, *ClientRequest) (*ClientResponse, error)
}

// UnimplementedReptileServer can be embedded to have forward compatible implementations.
type UnimplementedReptileServer struct {
}

func (*UnimplementedReptileServer) Request(ctx context.Context, req *ClientRequest) (*ClientResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Request not implemented")
}

func RegisterReptileServer(s *grpc.Server, srv ReptileServer) {
	s.RegisterService(&_Reptile_serviceDesc, srv)
}

func _Reptile_Request_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReptileServer).Request(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Reptile/Request",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReptileServer).Request(ctx, req.(*ClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Reptile_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Reptile",
	HandlerType: (*ReptileServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Request",
			Handler:    _Reptile_Request_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "reptile.proto",
}
